title: Virtual AppSec Israel 2020
description: OWASP AppSec Israel annual conference - 2020 edition!

# Since GH pages override this to "true", we test this value to see if we are running locally
safe: false

# Conference dates
dates: 27-28 October, 2018
trainingday: Tuesday, October 27th
confday: Wednesday, October 28th

sched: appsecisrael2020.sched.com
eventbrite: appsecil2020.eventbrite.com
